config/routes.rb
PennStation::Engine.routes.draw do

  root :to => 'pages#index'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"

  resources :activities
  resources :admins
  resources :analytics
  resources :calendars
  resources :calendar_subscriptions
  resources :events

  resources :folders do
    collection do
      get :images_for_imagepicker
    end
  end

  resources :image_picker, :only => [:index, :show]

  resources :media

  resources :pages do
    collection do
      get :reorder
    end
  end

  resources :scheduled_events
  resources :sections
  resources :sessions

  resources :slides do
    collection do
      get :images_for_imagepicker
    end
  end

  resources :slideshows
  resources :uploaded_files

end

app/models/penn_station/activity.rb
module PennStation
  class Activity < ActiveRecord::Base
    validates :administrator, presence: true
    validates :info, presence: true
    validates :operation, presence: true

    def message
      "#{administrator} #{operation} #{info}"
    end
  end
end

app/models/penn_station/address.rb
module PennStation
  class Address < ActiveRecord::Base
    validates :address1, presence: true
    validates :city,     presence: true
    validates :state,    presence: true
    validates :zipcode,  presence: true

    def activity_info
      "address #{address1}"
    end
  end
end

app/models/penn_station/admin.rb
# http://asciicasts.com/episodes/270-authentication-in-rails-3-1

module PennStation
  class Admin < ActiveRecord::Base
    has_secure_password

    validates :email, presence: true,
                      uniqueness: true

    validates :name, :presence => true,
                     :uniqueness => true

    validates :password, :length => { :minimum => 8, :if => :validate_password? },
                         :confirmation => { :if => :validate_password? }

    validates :password_confirmation, :length => { :minimum => 8, :if => :validate_password? },
                         :confirmation => { :if => :validate_password? }

    has_many :roles, autosave: true

    accepts_nested_attributes_for :roles, allow_destroy: true

    def activity_info
      "administrator #{name}"
    end

    def has_role?(*check_against)
      not (roles.map(&:name) & check_against).empty?
    end

    private

    def validate_password?
      password.present? || password_confirmation.present?
    end
  end
end

app/models/penn_station/analytics_setting.rb
module PennStation
  class AnalyticsSetting < ActiveRecord::Base

    # Analytics Module information
    # 
    # Module is registered at google cloud console for access only to Google Analytics API.
    #
    # GEMS
    # oauth2, https://github.com/intridea/oauth2, provides oauth2 authorization layer
    # legato, https://github.com/tpitale/legato, provides google analytics api v3 layer
    #
    #
    # OAUTH2
    # We use the Google Oauth2 "Installed Apps" flow. Normally used for desktop applications, but recommended
    # for content management system plugins.
    #
    # Basic flow:
    # 1. generate authorization url based on app's client id
    # 2. user visits authorization url and is prompted to authorize access for our app
    # 3. when user accepts, google generates authorization code
    # 4. user copies authorization code and submits it to app
    # 5. app uses authorization code to obtain access token and refresh token
    # 6. app uses access token to retrieve user analytics data. when access token expires, app uses
    #    refresh token to request new access token
    #
    # See https://developers.google.com/analytics/devguides/reporting/core/v3/gdataAuthorization#common_oauth
    #
    #
    # GOOGLE ANALYTICS API
    # See https://developers.google.com/analytics/devguides/reporting/core/v3/
    # and https://developers.google.com/analytics/devguides/config/mgmt/v3/
    #
    #
    # HIERARCHY OF ACCOUNTS, PROPERTIES, AND VIEWS (FORMERLY KNOWN AS PROFILES)
    # owner
    #   analytics account
    #   ...
    #   analytics account
    #     property <==> domain1.com <==> UA-XXXXXXXX-01
    #     ...
    #     property <==> domain5.com <==> UA-XXXXXXXX-05
    #       view1 = usually all analytics stats
    #       view2 = customized analytics stats
    #       view3 = customized analytics stats
    #       ...
    # 
    # See https://support.google.com/analytics/answer/1009618?hl=en&ref_topic=1102143&rd=1 
    #           



    # CCTS PS Analytics Module app info, from google cloud console https://cloud.google.com/console‎
    OAUTH_CLIENT_ID = "309649842280-svjb0s5v36iajuklrvmcr42o65cetbtg.apps.googleusercontent.com"
    OAUTH_CLIENT_SECRET = "PAaUIRQu9R3zVELblDSnmlcS"

  end
end

app/models/penn_station/calendar.rb
module PennStation
  class Calendar < ActiveRecord::Base
    validates :name, presence: true,
                     uniqueness: true

    has_many :calendar_subscriptions, class_name: "::PennStation::CalendarSubscription"
    has_many :pages, :through => :calendar_subscriptions

    has_and_belongs_to_many :scheduled_events, class_name: "::PennStation::ScheduledEvent"

    def activity_info
      "calendar #{name}"
    end
  end
end

app/models/penn_station/calendar_subscription.rb
module PennStation
  class CalendarSubscription < ActiveRecord::Base
    belongs_to :calendar, class_name: "::PennStation::Calendar"
    belongs_to :page, class_name: "::PennStation::Page"
  end
end

app/models/penn_station/event.rb
module PennStation
  class Event < ActiveRecord::Base
    validates :description, presence: true

    validates :name, presence: true

    validates :summary, presence: true

    has_many :scheduled_events, class_name: "::PennStation::ScheduledEvent"
    has_many :locations

    accepts_nested_attributes_for :locations
    accepts_nested_attributes_for :scheduled_events

    def has_calendar?(calendar)
      scheduled_events.map{|m| m.calendars.map{|m2| m2.name}}.flatten.include?(calendar.name)
    end

    def activity_info
      "event #{name}"
    end
  end
end

app/models/penn_station/folder.rb
module PennStation
  class Folder < ActiveRecord::Base
    validates :name, presence: true,
                     uniqueness: true

    has_many  :uploaded_files

    def activity_info
      "folder #{name}"
    end
  end
end

app/models/penn_station/location.rb
module PennStation
  class Location < ActiveRecord::Base
    belongs_to :event, class_name: "::PennStation::Event"
    belongs_to :address, class_name: "::PennStation::Address"

    accepts_nested_attributes_for :address
  end
end

app/models/penn_station/media.rb
module PennStation
  class Media

    def self.all
      Folder.all.order(:name).includes(:uploaded_files) +
      Slideshow.all.order(:name).includes(:slides)
    end
  end
end

app/models/penn_station/page.rb
module PennStation
  class Page < ActiveRecord::Base
    attr_accessor :parent_url

    validates :position, presence: true,
                         numericality: { :greater_than_or_equal_to => 0 }

    validates :ptype, format: { :with => /\A[a-zA-Z\d]+\z/ }

    validates :published, inclusion: { :in => [true, false] }

    validates :show_in_nav, inclusion: { :in => [true, false] }

    validates :title, presence: true,
                      uniqueness: true

    validates :url, presence: true,
                    uniqueness: true

    before_validation :urlize

    before_validation :set_defaults, :on => :create

    after_find do |page|
      if ptype == 'HomePage'
        self.parent_url = ''
      else
        parent = url.split('/')[0..-2].join('/')
        parent = '/' if parent.empty?
        self.parent_url = parent
      end
    end

    has_many :sections, :dependent => :destroy

    has_many :calendar_subscriptions, class_name: "::PennStation::CalendarSubscription"
    has_many :calendars, :through => :calendar_subscriptions

    def self.lookup(url)
      self.where(url: (url == '/') ? '/' : "/#{url}").first
    end

    def self.top_level(page)
      return page if page.parent_url == '/' or page.url == '/'
      self.where(url: '/' + page.url.split('/')[1]).first
    end

    def parent
      Page.where(url: parent_url).first
    end

    def home_page?
      url == '/'
    end

    def activity_info
      "page #{title}"
    end

    private

    def urlize
      if (ptype == 'HomePage') || (title == 'HomePage')
        self.url = '/'
      else
        self.url = (parent_url || '/')
        self.url += '/' unless url[-1] == '/'
        self.url += (title || '').gsub(/ /, "_").gsub(/[^\d\w\-_]/, "").downcase
      end
    end

    def set_defaults
      self.published = home_page?
      self.show_in_nav = true
      self.sections << Section.new(name: 'main', content: '<h1>main</h1>')
      self.position = 0 if position.nil?

      default_page_type
      true
    end

    def default_page_type
      if home_page?
        self.ptype = 'HomePage'
      else
        self.ptype ||= 'Page'
      end
    end
  end
end

app/models/penn_station/page_tree.rb
require 'rubytree'

module PennStation

  class PageTree
    attr_accessor :root

    def initialize
      self.root = Tree::TreeNode.new("/", Page.lookup('/'))
      build_tree
      self
    end

    def build_tree
      Page.all.sort{|a,b| a.url <=> b.url}.each do |page|
        current_node = root
        page.url.split('/').each do |url_component|
          next if url_component.blank?
          current_node = add_child(current_node,url_component,page)
        end
      end
    end

    def add_child(root,name,content)
      begin root << Tree::TreeNode.new(name,content) rescue nil end
      root[name]
    end

    def find(page, start=root)
      return start if start.content.id == page.id

      found = nil
      unless start.children.empty?
        start.children.each do |child|
          found = find(page,child)
          return found if found
        end
      end
      found
    end

    def ordered_find(search=nil)
      tree = self
      target = search.nil? ? tree.root.content : search
      tree.find(target).children.select{|p| p.content.published and p.content.show_in_nav }.sort{|a,b| a.content.position <=> b.content.position}
    end

    def self.ordered_find(search=nil)
      # Purpose not documented by original author.
      self.new.ordered_find(search)
    end
  end
end

app/models/penn_station/role.rb
module PennStation
  class Role < ActiveRecord::Base

    LIST = [ "editor", "admin", "pennstation_admin" ]

    validates_associated :admin

    validates :name, presence: true,
                     inclusion: { :in => LIST }

    belongs_to :admin

    def self.available
      LIST
    end

    def assignable_roles(admin)

        # order matters here - most powerful to least powerful

      return LIST if admin.roles.map(&:name).include?("pennstation_admin")
      return [ "editor", "admin" ] if admin.roles.map(&:name).include?("admin")
      []
    end
  end
end

app/models/penn_station/scheduled_event.rb
module PennStation
  class CalendarScheduledEvent < ActiveRecord::Base
  end

  class ScheduledEvent < ActiveRecord::Base
    has_and_belongs_to_many :calendars, class_name: "::PennStation::Calendar"
    belongs_to              :event, class_name: "::PennStation::Event"

    accepts_nested_attributes_for :calendars

    def status
      return 'Upcoming' if starts_at > Date.today
      return 'Closed' if ends_at < Date.today
      'Current'
    end
  end
end

app/models/penn_station/section.rb
module PennStation
  class Section < ActiveRecord::Base
    validates :content, presence: true

    validates :name, presence: true

    before_validation :set_defaults, :on => :create

    belongs_to :page

    def activity_info
      "page #{page.title}, section #{name}"
    end

    private

    def set_defaults
      self.content = "<h1>#{name}</h1>"
      true
    end
  end
end

app/models/penn_station/slide.rb
require 'file_size_validator'

module PennStation
  class Slide < ActiveRecord::Base
    mount_uploader :image, SlideUploader

    belongs_to  :slideshow

    validates :title, presence: true
    validates :image, :presence => true,
                      :file_size => { :maximum => 5.megabytes.to_i }

    before_save :update_file_attributes

    def activity_info
      "uploaded image to slideshow #{slideshow.name}"
    end

    private

    def update_file_attributes
      if image.present? && image_changed?
        self.content_type = image.file.content_type
        self.size = image.file.size
      end
    end

  end
end

app/models/penn_station/slideshow.rb
module PennStation
  class Slideshow < ActiveRecord::Base
    validates :name, presence: true,
                     uniqueness: true

    has_many :slides, -> { order 'position' }

    def activity_info
      "slideshow #{name}"
    end
  end
end

app/models/penn_station/uploaded_file.rb
require 'file_size_validator'

module PennStation
  class UploadedFile < ActiveRecord::Base
    mount_uploader :file, MediaUploader

    validates  :file, :presence => true,
                      :file_size => { :maximum => 45.megabytes.to_i }

    belongs_to :folder

    before_save :update_file_attributes

    def activity_info
      "uploaded file to folder #{folder.name}"
    end

    def filename
      File.basename(file.path)
    end

    private

    def update_file_attributes
      if file.present? && file_changed?
        self.content_type = file.file.content_type
        self.size = file.file.size
      end
    end
  end
end

app/controllers/penn_station/activities_controller.rb
require_dependency "penn_station/application_controller"

module PennStation
  class ActivitiesController < ApplicationController
    def index
      @activities = Activity.all.order("created_at desc")
    end
  end
end

app/controllers/penn_station/admins_controller.rb
require_dependency "penn_station/application_controller"

module PennStation
  class AdminsController < ApplicationController
    before_action :set_admin, only: [:show, :edit, :update, :destroy]

    track_admin_activity

    def index
      @admins = Admin.order(:name)
    end

    def show
    end

    def new
      @admin = Admin.new
      generate_roles_list
    end

    def edit
      generate_roles_list
    end

    def create
      @admin = Admin.new(admin_params)

      if @admin.save
        redirect_to @admin, notice: "Administrator #{@admin.name} was successfully created."
      else
        generate_roles_list
        render action: 'new'
      end
    end

    def update
      if @admin.update(admin_params)
        redirect_to edit_admin_path(@admin), notice: "Successfully updated Administrator #{@admin.name}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @admin.destroy
      redirect_to admins_url, notice: "Administrator #{@admin.name} was successfully deleted."
    end

    private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def admin_params
      plist = params.require(:admin).permit(:name, :email, :password, :password_confirmation, roles_attributes: [:id,:name])

        # mark any associated roles that were unchecked for destruction.

      if plist.has_key?("roles_attributes")
        plist["roles_attributes"].each do |k,v|
         v["_destroy"] = true unless v.has_key?("name")
        end
      end

      plist
    end

    def generate_roles_list
      (PennStation::Role.available - @admin.roles.map(&:name)).each do |available_role|
        next unless current_admin.has_role?(available_role)
        @admin.roles.build(name: available_role)
      end
    end
  end
end

app/views/penn_station/pages/_calendars_panel.html.erb
<%= form_for calendar do |f| %>
  <div>
    <h3>Events</h3>
    <%# calendar.scheduled_events.each do |scheduled_event| %>
      <%= render(:partial => "penn_station/scheduled_events/index", :locals => {:scheduled_events => calendar.scheduled_events}) %>
    <%# end %>
  </div>
<% end %>

app/views/penn_station/pages/_form.html.erb
<% if page.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in page.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render(:partial => "penn_station/pages/panels_header", :locals => {:sections => page.sections}) %>

<div class="panels" data-pennstation-ptype="<%= @page.ptype %>">
  <%= render(:partial => "penn_station/pages/properties_panel", :locals => {:page => page}) %>

  <% page.sections.each do |section| %>
    <div id="<%= section.name.gsub(/\s/,'_') %>_panel" class="panel" style="display: none;">

      <% begin %>
        <%= render(:partial => "penn_station/pages/#{section.name.gsub(/\s/,'_')}_panel", :locals => {:page => page, :section => section}) %>
      <% rescue %>
        <%= render(:partial => "penn_station/pages/sections_panel", :locals => {:page => page, :section => section}) %>
      <% end %>

      <form action="/admin/uploaded_files?folder_id=<%= @page.url[1..-1] %>" class="dropzone" style="border: 2px solid black; min-height: 200px;">
        <div class="dz-default dz-message"><span>Drag-and-drop files here to upload, or click to browse files</span></div>
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
      </form>

      <ol style="clear: both;" class="uploaded_files_gallery">
        <% folder = PennStation::Folder.where(name: @page.url.gsub('/','')).first %>
        <% if folder.present? %>
          <% folder.uploaded_files.each do |fname| %>
            <li>
              <% if fname.content_type.include? 'image' %>
                <a href="<%= fname.file.to_s %>" target="_blank"><img src="<%= fname.file.url(:tiny) %>"/></a>
              <% else %>
                <a href="<%= fname.file.to_s %>" target="_blank"><%= File.basename(fname.file.to_s) %></a>
              <% end %>
              <div class="obj_delete">X</div>
            </li>
          <% end %>
        <% end %>
      </ol>
    </div>
  <% end %>

  <% page.calendars.each do |calendar| %>
    <div id="<%= calendar.name.gsub(/\s/,'_') %>_panel" class="panel" style="display: none;">

      <% begin %>
        <%= render(:partial => "penn_station/pages/#{calendar.name.gsub(/\s/,'_')}_panel", :locals => {:page => page, :calendar => calendar}) %>
      <% rescue %>
        <%= render(:partial => "penn_station/pages/calendars_panel", :locals => {:page => page, :calendar => calendar}) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/penn_station/pages/_page_index_row.html.erb
<% unless node.nil? %>
  <% page = node.content %>
  <li id="<%= page.id %>" class="row">
    <ol class="cols">
      <li class="title">
          <a href="<%= edit_page_path(page) %>"><%= page.title %>
            <%= image_tag("edit.png", class: "normal") %>
            <%= image_tag("edit_over.png", class: "hover") %>
          </a>
      </li>

      <li class="add-sub-page" style="clear: both;">
        <a href="<%= new_page_path(page: {parent_url: page.url}) %>">
          <%= image_tag("plus.png", class: "normal2") %>
          <%= image_tag("plus_over.png", class: "hover2") %>
          Add a sub-page
        </a>
      </li>

      <li class="details">
        <ol>
          <% if current_admin.has_role?("pennstation_admin") %>
            <li class="page-type">
              <%= page.ptype %>
            </li>
          <% end %>

          <li class="published">
            <%= image_tag("check.png") if page.published %>
          </li>

          <li class="updated-at"><%= page.updated_at.in_time_zone("Eastern Time (US & Canada)").strftime("%m-%d-%Y@%I:%0l%P") %></li>
        </li>
      </ol>
    </ol>
  </li>

  <% if node.children.size > 0 %>
    <ol class="xcols">
      <% node.children.sort_by{|s| s.content.position}.map do |child| %>
        <%= render(:partial => "penn_station/pages/page_index_row", :locals => {:node => child}) %>
      <% end %>
    </ol>
  <% end %>
<% end %>

app/views/penn_station/pages/_panels_header.html.erb
<header id="panels">
  <ul id="panel_tabs">
    <% unless sections.empty? %>
      <li data-panel-id="properties_panel" class="current">Properties</li>

      <% sections.each do |section| %>
        <li id="<%= section.name %>_section" data-panel-id="<%= section.name %>_panel"><%= section.name.capitalize %></li>
      <% end %>

      <% @page.calendars.each do |calendar| %>
        <li id="<%= calendar.name %>_calendar" data-panel-id="<%= calendar.name %>_panel"><%= calendar.name %></li>
      <% end %>
    <% end %>
  </ul>

  <ul id="panel_ops">
    <li id="save">Save</li>
    <li id="save_and_preview">Save and Preview</li>
  </ul>

  <div style="clear: both;">&nbsp</div>
</header>

app/views/penn_station/pages/_properties_panel.html.erb
<div id="properties_panel" class="panel current">
<%=form_for page do |f| %>
  <%#= f.error_messages %>
  <%= f.hidden_field :parent_url %>

  <div>
    <%=f.label :title %>
    <%=f.text_field :title, :autofocus => (page.new_record?) ? true : false %>
  </div>

  <% if current_admin.has_role?("pennstation_admin") %>
    <div>
      <%=f.label :ptype, 'Page Type' %>
      <%=f.text_field :ptype %>
    </div>
  <% end %>

  <% unless page.new_record? %>
    <div class="radio_buttons">
      <span class="label">Show in Navigation Menu?</span>
      <div>
        <%= f.radio_button :show_in_nav, "1", :checked => page.show_in_nav %>
        <%=f.label :show_in_nav, "Yes"%>
      </div>

      <div>
        <%= f.radio_button :show_in_nav, "0", :checked => !page.show_in_nav %>
        <%=f.label :show_in_nav, "No"%>
      </div>
    </div>

    <div class="radio_buttons">
      <span class="label">Publication status</span>
      <div>
        <%= f.radio_button :published, "1", :checked => page.published %>
        <%=f.label :published, "Published (visible to everyone)"%>
      </div>

      <div>
        <%= f.radio_button :published, "0", :checked => !page.published %>
        <%=f.label :published, "Draft (only visible to editors)"%>
      </div>
    </div>

    <div id="seo_properties">
      <div>
        <%=f.label :seo_title %>
        <%= f.text_field :seo_title %>
      </div>
      <div>
        <%=f.label :seo_keywords %>
        <%= f.text_field :seo_keywords %>
      </div>
      <div>
        <%=f.label :seo_description %>
        <%= f.text_area :seo_description, :style => "height: 50px;"%>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/penn_station/pages/_reorder.html.erb
<% content_for :toolbar_links do %>
  <li><a href="<%= pages_path %>">Back to all Pages</a></li>
<% end %>

<h1>Reorder pages</h1>
<p style="margin-bottom: 20px;">Drag and drop pages into desired order.</p>
<ol class="sortable">
  <%= render(:partial => "penn_station/pages/reorder_page_index_row", :locals => {:node => @pages.root}) %>
</ol>

app/views/penn_station/pages/_reorder_page_index_row.html.erb
<% unless node.nil? %>
  <% page = node.content %>
  <li id="page_<%= page.id %>" class="row">
    <div><%= page.title %></div>
    <% if node.children.size > 0 %>
      <% node.children.sort_by{|s| s.content.position}.map do |child| %>
      <ol>
        <%= render(:partial => "penn_station/pages/reorder_page_index_row", :locals => {:node => child}) %>
      </ol>
      <% end %>
    <% end %>
  </li>
<% end %>

app/views/penn_station/pages/_sections_panel.html.erb
<%=form_for section do |f| %>
  <%= f.hidden_field :page_id %>
  <%= f.hidden_field :name %>
  <div>
    <%=f.text_area :content , :id => "#{section.name}_content", :class => "tinymce", :rows => 40, :cols => 100 %>
    <div class="moreinfolink" style="display: none;">
      <%=f.label :moreinfo_url, 'More info url' %>
      <%= f.text_field :moreinfo_url %>
    </div>
  </div>
<% end %>

app/views/penn_station/pages/create.html.erb
<h1>Successfully updated <%= @page.title %></h1>

app/views/penn_station/pages/edit.html.erb
<% content_for :toolbar_links do %>
  <li><a href="<%= pages_path %>">Back to all Pages</a></li>
  <li><%= link_to "Delete this page", @page, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
  <% if current_admin.has_role?("pennstation_admin") %>
    <li><%= link_to "Add new section", new_section_path(page_id: @page.id) %></li>
    <% @page.sections.each do |section| %>
      <% next if section.name == 'main' %>
      <li><%= link_to "Edit section #{section.name}", edit_section_path(section,page_id: @page.id) %></li>
      <li><%= link_to "Delete section #{section.name}", section, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
    <% end %>
    <li><%= link_to "Add new calendar", new_calendar_subscription_path(page_id: @page.id) %></li>
  <% end %>
<% end %>

<div id="<%= controller.controller_name %>">
  <h1>Edit <%= @page.title %></h1>
  <%= render(:partial => "penn_station/pages/form", :locals => {:page => @page}) %>
</div>

app/views/penn_station/pages/index.html.erb
<% if params.has_key?('reorder') %>
  <%= render :partial => 'reorder' %>
<% else %>

  <% content_for :toolbar_links do %>
     <li class="page"><a href="<%= pages_path(:reorder => 1) %>">Reorder Pages</a></li>
  <% end %>

  <h1>Manage <%= controller.controller_name %></h1>

  <ol id="<%= controller.controller_name %>_index" class="index">
    <li class="title-row row">
      <ol class="cols">
        <li class="title-row-col">Title</li>
        <li class="details">
          <ol>
            <% if current_admin.has_role?("pennstation_admin") %>
              <li class="page-type">Page Type</li>
            <% end %>
            <li class="published">Published?</li>
            <li class="updated-at">Last Updated</li>
          </ol>
        </li>
      </ol>
    </li>

    <%= render(:partial => "penn_station/pages/page_index_row", :locals => {:node => @pages.root}) %>
  </ol>
<% end %>

app/views/penn_station/pages/index.js.erb
<%= page_tree_for_link_picker(@pages.root) %>

<script type="text/javascript">
$('#internal_list a').each(function(idx, link){
  var href = link.href.replace(window.location.protocol + '//' + window.location.host,'');
  if($('#internal_href').val() == href) $(link).addClass('current');
  $(link).click(function(e){
    $('#internal_href').val(href);
    $('#internal_list a').removeClass('current');
    $(this).addClass('current');
    return false; // equivalent to e.preventDefault() + e.stopPropagation()  
  });
});
</script>

app/views/penn_station/pages/new.html.erb
<% content_for :toolbar_links do %>
  <li><a href="<%= pages_path %>">Back to all Pages</a></li>
<% end %>

<%= render 'penn_station/shared/flash_messages' unless flash.empty? %>

<%#= error_messages_for :page %>

<h1>Create a new <%= controller.controller_name.singularize %></h1>
<%= render(:partial => "penn_station/pages/form", :locals => {:page => @page}) %>

app/views/penn_station/pages/show.html.erb
<% content_for :toolbar_links do %>
  <li><a href="<%= pages_path %>">Back to all Pages</a></li>
  <li><%= link_to "Delete this page", @page, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
<% end %>

<div id="<%= controller.controller_name %>">
  <h1>Show <%= @page.title %></h1>
  <%= render(:partial => "penn_station/pages/form", :locals => {:page => @page}) %>
</div>