config/routes.rb
PennStation::Engine.routes.draw do

  root :to => 'pages#index'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"

  resources :activities
  resources :admins
  resources :analytics
  resources :calendars
  resources :calendar_subscriptions
  resources :events

  resources :folders do
    collection do
      get :images_for_imagepicker
    end
  end

  resources :image_picker, :only => [:index, :show]

  resources :media

  resources :pages do
    collection do
      get :reorder
    end
  end

  resources :scheduled_events
  resources :sections
  resources :sessions

  resources :slides do
    collection do
      get :images_for_imagepicker
    end
  end

  resources :slideshows
  resources :uploaded_files

end

app/models/penn_station/activity.rb
module PennStation
  class Activity < ActiveRecord::Base
    validates :administrator, presence: true
    validates :info, presence: true
    validates :operation, presence: true

    def message
      "#{administrator} #{operation} #{info}"
    end
  end
end

app/models/penn_station/address.rb
module PennStation
  class Address < ActiveRecord::Base
    validates :address1, presence: true
    validates :city,     presence: true
    validates :state,    presence: true
    validates :zipcode,  presence: true

    def activity_info
      "address #{address1}"
    end
  end
end

app/models/penn_station/admin.rb
# http://asciicasts.com/episodes/270-authentication-in-rails-3-1

module PennStation
  class Admin < ActiveRecord::Base
    has_secure_password

    validates :email, presence: true,
                      uniqueness: true

    validates :name, :presence => true,
                     :uniqueness => true

    validates :password, :length => { :minimum => 8, :if => :validate_password? },
                         :confirmation => { :if => :validate_password? }

    validates :password_confirmation, :length => { :minimum => 8, :if => :validate_password? },
                         :confirmation => { :if => :validate_password? }

    has_many :roles, autosave: true

    accepts_nested_attributes_for :roles, allow_destroy: true

    def activity_info
      "administrator #{name}"
    end

    def has_role?(*check_against)
      not (roles.map(&:name) & check_against).empty?
    end

    private

    def validate_password?
      password.present? || password_confirmation.present?
    end
  end
end

app/models/penn_station/analytics_setting.rb
module PennStation
  class AnalyticsSetting < ActiveRecord::Base

    # Analytics Module information
    # 
    # Module is registered at google cloud console for access only to Google Analytics API.
    #
    # GEMS
    # oauth2, https://github.com/intridea/oauth2, provides oauth2 authorization layer
    # legato, https://github.com/tpitale/legato, provides google analytics api v3 layer
    #
    #
    # OAUTH2
    # We use the Google Oauth2 "Installed Apps" flow. Normally used for desktop applications, but recommended
    # for content management system plugins.
    #
    # Basic flow:
    # 1. generate authorization url based on app's client id
    # 2. user visits authorization url and is prompted to authorize access for our app
    # 3. when user accepts, google generates authorization code
    # 4. user copies authorization code and submits it to app
    # 5. app uses authorization code to obtain access token and refresh token
    # 6. app uses access token to retrieve user analytics data. when access token expires, app uses
    #    refresh token to request new access token
    #
    # See https://developers.google.com/analytics/devguides/reporting/core/v3/gdataAuthorization#common_oauth
    #
    #
    # GOOGLE ANALYTICS API
    # See https://developers.google.com/analytics/devguides/reporting/core/v3/
    # and https://developers.google.com/analytics/devguides/config/mgmt/v3/
    #
    #
    # HIERARCHY OF ACCOUNTS, PROPERTIES, AND VIEWS (FORMERLY KNOWN AS PROFILES)
    # owner
    #   analytics account
    #   ...
    #   analytics account
    #     property <==> domain1.com <==> UA-XXXXXXXX-01
    #     ...
    #     property <==> domain5.com <==> UA-XXXXXXXX-05
    #       view1 = usually all analytics stats
    #       view2 = customized analytics stats
    #       view3 = customized analytics stats
    #       ...
    # 
    # See https://support.google.com/analytics/answer/1009618?hl=en&ref_topic=1102143&rd=1 
    #           



    # CCTS PS Analytics Module app info, from google cloud console https://cloud.google.com/console‎
    OAUTH_CLIENT_ID = "309649842280-svjb0s5v36iajuklrvmcr42o65cetbtg.apps.googleusercontent.com"
    OAUTH_CLIENT_SECRET = "PAaUIRQu9R3zVELblDSnmlcS"

  end
end

app/models/penn_station/calendar.rb
module PennStation
  class Calendar < ActiveRecord::Base
    validates :name, presence: true,
                     uniqueness: true

    has_many :calendar_subscriptions, class_name: "::PennStation::CalendarSubscription"
    has_many :pages, :through => :calendar_subscriptions

    has_and_belongs_to_many :scheduled_events, class_name: "::PennStation::ScheduledEvent"

    def activity_info
      "calendar #{name}"
    end
  end
end

app/models/penn_station/calendar_subscription.rb
module PennStation
  class CalendarSubscription < ActiveRecord::Base
    belongs_to :calendar, class_name: "::PennStation::Calendar"
    belongs_to :page, class_name: "::PennStation::Page"
  end
end

app/models/penn_station/event.rb
module PennStation
  class Event < ActiveRecord::Base
    validates :description, presence: true

    validates :name, presence: true

    validates :summary, presence: true

    has_many :scheduled_events, class_name: "::PennStation::ScheduledEvent"
    has_many :locations

    accepts_nested_attributes_for :locations
    accepts_nested_attributes_for :scheduled_events

    def has_calendar?(calendar)
      scheduled_events.map{|m| m.calendars.map{|m2| m2.name}}.flatten.include?(calendar.name)
    end

    def activity_info
      "event #{name}"
    end
  end
end

app/models/penn_station/folder.rb
module PennStation
  class Folder < ActiveRecord::Base
    validates :name, presence: true,
                     uniqueness: true

    has_many  :uploaded_files

    def activity_info
      "folder #{name}"
    end
  end
end

app/models/penn_station/location.rb
module PennStation
  class Location < ActiveRecord::Base
    belongs_to :event, class_name: "::PennStation::Event"
    belongs_to :address, class_name: "::PennStation::Address"

    accepts_nested_attributes_for :address
  end
end

app/models/penn_station/media.rb
module PennStation
  class Media

    def self.all
      Folder.all.order(:name).includes(:uploaded_files) +
      Slideshow.all.order(:name).includes(:slides)
    end
  end
end

app/models/penn_station/page.rb
module PennStation
  class Page < ActiveRecord::Base
    attr_accessor :parent_url

    validates :position, presence: true,
                         numericality: { :greater_than_or_equal_to => 0 }

    validates :ptype, format: { :with => /\A[a-zA-Z\d]+\z/ }

    validates :published, inclusion: { :in => [true, false] }

    validates :show_in_nav, inclusion: { :in => [true, false] }

    validates :title, presence: true,
                      uniqueness: true

    validates :url, presence: true,
                    uniqueness: true

    before_validation :urlize

    before_validation :set_defaults, :on => :create

    after_find do |page|
      if ptype == 'HomePage'
        self.parent_url = ''
      else
        parent = url.split('/')[0..-2].join('/')
        parent = '/' if parent.empty?
        self.parent_url = parent
      end
    end

    has_many :sections, :dependent => :destroy

    has_many :calendar_subscriptions, class_name: "::PennStation::CalendarSubscription"
    has_many :calendars, :through => :calendar_subscriptions

    def self.lookup(url)
      self.where(url: (url == '/') ? '/' : "/#{url}").first
    end

    def self.top_level(page)
      return page if page.parent_url == '/' or page.url == '/'
      self.where(url: '/' + page.url.split('/')[1]).first
    end

    def parent
      Page.where(url: parent_url).first
    end

    def home_page?
      url == '/'
    end

    def activity_info
      "page #{title}"
    end

    private

    def urlize
      if (ptype == 'HomePage') || (title == 'HomePage')
        self.url = '/'
      else
        self.url = (parent_url || '/')
        self.url += '/' unless url[-1] == '/'
        self.url += (title || '').gsub(/ /, "_").gsub(/[^\d\w\-_]/, "").downcase
      end
    end

    def set_defaults
      self.published = home_page?
      self.show_in_nav = true
      self.sections << Section.new(name: 'main', content: '<h1>main</h1>')
      self.position = 0 if position.nil?

      default_page_type
      true
    end

    def default_page_type
      if home_page?
        self.ptype = 'HomePage'
      else
        self.ptype ||= 'Page'
      end
    end
  end
end

app/models/penn_station/page_tree.rb
require 'rubytree'

module PennStation

  class PageTree
    attr_accessor :root

    def initialize
      self.root = Tree::TreeNode.new("/", Page.lookup('/'))
      build_tree
      self
    end

    def build_tree
      Page.all.sort{|a,b| a.url <=> b.url}.each do |page|
        current_node = root
        page.url.split('/').each do |url_component|
          next if url_component.blank?
          current_node = add_child(current_node,url_component,page)
        end
      end
    end

    def add_child(root,name,content)
      begin root << Tree::TreeNode.new(name,content) rescue nil end
      root[name]
    end

    def find(page, start=root)
      return start if start.content.id == page.id

      found = nil
      unless start.children.empty?
        start.children.each do |child|
          found = find(page,child)
          return found if found
        end
      end
      found
    end

    def ordered_find(search=nil)
      tree = self
      target = search.nil? ? tree.root.content : search
      tree.find(target).children.select{|p| p.content.published and p.content.show_in_nav }.sort{|a,b| a.content.position <=> b.content.position}
    end

    def self.ordered_find(search=nil)
      # Purpose not documented by original author.
      self.new.ordered_find(search)
    end
  end
end

app/models/penn_station/role.rb
module PennStation
  class Role < ActiveRecord::Base

    LIST = [ "editor", "admin", "pennstation_admin" ]

    validates_associated :admin

    validates :name, presence: true,
                     inclusion: { :in => LIST }

    belongs_to :admin

    def self.available
      LIST
    end

    def assignable_roles(admin)

        # order matters here - most powerful to least powerful

      return LIST if admin.roles.map(&:name).include?("pennstation_admin")
      return [ "editor", "admin" ] if admin.roles.map(&:name).include?("admin")
      []
    end
  end
end

app/models/penn_station/scheduled_event.rb
module PennStation
  class CalendarScheduledEvent < ActiveRecord::Base
  end

  class ScheduledEvent < ActiveRecord::Base
    has_and_belongs_to_many :calendars, class_name: "::PennStation::Calendar"
    belongs_to              :event, class_name: "::PennStation::Event"

    accepts_nested_attributes_for :calendars

    def status
      return 'Upcoming' if starts_at > Date.today
      return 'Closed' if ends_at < Date.today
      'Current'
    end
  end
end

app/models/penn_station/section.rb
module PennStation
  class Section < ActiveRecord::Base
    validates :content, presence: true

    validates :name, presence: true

    before_validation :set_defaults, :on => :create

    belongs_to :page

    def activity_info
      "page #{page.title}, section #{name}"
    end

    private

    def set_defaults
      self.content = "<h1>#{name}</h1>"
      true
    end
  end
end

app/models/penn_station/slide.rb
require 'file_size_validator'

module PennStation
  class Slide < ActiveRecord::Base
    mount_uploader :image, SlideUploader

    belongs_to  :slideshow

    validates :title, presence: true
    validates :image, :presence => true,
                      :file_size => { :maximum => 5.megabytes.to_i }

    before_save :update_file_attributes

    def activity_info
      "uploaded image to slideshow #{slideshow.name}"
    end

    private

    def update_file_attributes
      if image.present? && image_changed?
        self.content_type = image.file.content_type
        self.size = image.file.size
      end
    end

  end
end

app/models/penn_station/slideshow.rb
module PennStation
  class Slideshow < ActiveRecord::Base
    validates :name, presence: true,
                     uniqueness: true

    has_many :slides, -> { order 'position' }

    def activity_info
      "slideshow #{name}"
    end
  end
end

app/models/penn_station/uploaded_file.rb
require 'file_size_validator'

module PennStation
  class UploadedFile < ActiveRecord::Base
    mount_uploader :file, MediaUploader

    validates  :file, :presence => true,
                      :file_size => { :maximum => 45.megabytes.to_i }

    belongs_to :folder

    before_save :update_file_attributes

    def activity_info
      "uploaded file to folder #{folder.name}"
    end

    def filename
      File.basename(file.path)
    end

    private

    def update_file_attributes
      if file.present? && file_changed?
        self.content_type = file.file.content_type
        self.size = file.file.size
      end
    end
  end
end

app/controllers/penn_station/activities_controller.rb
require_dependency "penn_station/application_controller"

module PennStation
  class ActivitiesController < ApplicationController
    def index
      @activities = Activity.all.order("created_at desc")
    end
  end
end

app/controllers/penn_station/admins_controller.rb
require_dependency "penn_station/application_controller"

module PennStation
  class AdminsController < ApplicationController
    before_action :set_admin, only: [:show, :edit, :update, :destroy]

    track_admin_activity

    def index
      @admins = Admin.order(:name)
    end

    def show
    end

    def new
      @admin = Admin.new
      generate_roles_list
    end

    def edit
      generate_roles_list
    end

    def create
      @admin = Admin.new(admin_params)

      if @admin.save
        redirect_to @admin, notice: "Administrator #{@admin.name} was successfully created."
      else
        generate_roles_list
        render action: 'new'
      end
    end

    def update
      if @admin.update(admin_params)
        redirect_to edit_admin_path(@admin), notice: "Successfully updated Administrator #{@admin.name}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @admin.destroy
      redirect_to admins_url, notice: "Administrator #{@admin.name} was successfully deleted."
    end

    private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def admin_params
      plist = params.require(:admin).permit(:name, :email, :password, :password_confirmation, roles_attributes: [:id,:name])

        # mark any associated roles that were unchecked for destruction.

      if plist.has_key?("roles_attributes")
        plist["roles_attributes"].each do |k,v|
         v["_destroy"] = true unless v.has_key?("name")
        end
      end

      plist
    end

    def generate_roles_list
      (PennStation::Role.available - @admin.roles.map(&:name)).each do |available_role|
        next unless current_admin.has_role?(available_role)
        @admin.roles.build(name: available_role)
      end
    end
  end
end

app/views/penn_station/scheduled_events/_form.html.erb
<%= form_for scheduled_event do |f| %>
  <% if scheduled_event.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in scheduled_event.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset id="calendars">
    <legend>Add the event to these calendars</legend>
    <div class="field">

      <%= link_to "Add/Manage calendars", penn_station.calendars_path %>
      <div class="calendars">
        <% PennStation::Calendar.all.each do |calendar| %>
          <div class="field">
            <%= check_box_tag :calendar_ids, calendar.id, false, :name => 'calendar[calendar_ids][]' %>
            <label><%= calendar.name %></label>
          </div>
        <% end %>
      </div>
    </div>
  </fieldset>

  <fieldset id="events">
    <legend>Event details</legend>
    <div class="field">
<!--
      <%#= link_to "Add/Manage event details", penn_station.events_path %>
-->
      <%= f.fields_for :events do |e| %>
<!--
        <%# unless PennStation::Event.count.zero? %>
          <div class="field">
            <%#= e.label :name %>
            <%#= select("", "event_id", PennStation::Event.all.order('name').collect {|p| [ p.name, p.id ] } ) %>
          </div>
        <%# end %>
-->

        <div class="field">
          <%= e.label :name %>
          <%= e.text_field :name %>
        </div>

        <div class="field">
          <%= e.label :summary %>
          <%= e.text_field :summary %>
        </div>

        <div class="field">
          <%= e.label :description %>
          <%= e.text_area :description , :id => "description", :class => "tinymce", :rows => 10, :cols => 100 %>
        </div>
      <% end %>
    </div>
  </fieldset>

  <fieldset id="event_dates">
  <legend>Event date/time info</legend>
    <div>
      <div class="field">
        <%= f.label :starts_at %>
        <%= f.date_select :starts_at, {order: [:month, :day, :year]} %>
      </div>

      <div class="field">
        <%= f.label :ends_at %>
        <%= f.date_select :ends_at, {order: [:month, :day, :year]} %>
      </div>
    </div>

    <div class="field">
      <%= f.label :times %>
      <%= f.text_area :times ,:rows => 10, :cols => 40 %>
    </div>
  </fieldset>

  <fieldset id="location">
    <legend>Location</legend>
    <%= f.fields_for :locations do |l| %>
      <div class="field">
        <% unless PennStation::Location.count.zero? %>
          <%= l.label :name %>
          <%= select("", "location_id", PennStation::Location.all.order('name').collect {|p| [ p.name, p.id ] } ) %>
        <% end %>

        <div class="field">
          <%= l.label :name %>
          <%= l.text_field :name %>
        </div>

        <div class="address">
          <%= l.fields_for :addresses do |a| %>
            <% unless PennStation::Address.count.zero? %>
              <%= a.label :address, 'Existing Addresses' %>
              <%= select("", "address_id", PennStation::Address.all.order('address1').collect {|p| [ "#{p.address1}, #{p.address2}, #{p.city}, #{p.state}, #{p.zipcode}", p.id ] } ) %>
            <% end %>

            <div class="field">
              <%= a.label :address1 %>
              <%= a.text_field :address1 %>
            </div>

            <div class="field">
              <%= a.label :address2 %>
              <%= a.text_field :address2 %>
            </div>

            <div class="field">
              <%= a.label :city %>
              <%= a.text_field :city %>
            </div>

            <div class="field">
              <%= a.label :state %>
              <%= a.text_field :state %>
            </div>

            <div class="field">
              <%= a.label :zipcode %>
              <%= a.text_field :zipcode %>
            </div>

            <div class="field">
              <%= a.label :directions %>
              <%= a.text_area :directions,:rows => 10, :cols => 100 %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </fieldset>

  <div class="actions"><%= f.submit 'Save' %></div>
<% end %>

app/views/penn_station/scheduled_events/_index.html.erb
<% content_for :toolbar_links do %>
  <% if current_admin.has_role?("admin") %>
    <li class="event"><a href="<%= new_event_path %>">Add a new event</a></li>
  <% end %>
<% end %>

<ol id="<%= controller.controller_name %>_index" class="index">
  <li class="title-row row">
    <ol class="">
      <li class="name">Name</li>
      <li class="status">Status</li>
      <li class="starts_at">Starts At</li>
      <li class="calendar">Calendar</li>
    </ol>
  </li>

  <% scheduled_events.each do |scheduled_event| %>
<%# binding.pry %>
<%# next if event.scheduled_events.empty? %>
    <li id="<%= scheduled_event.id %>" class="row <%= cycle("even", "odd") -%>">
      <ol class="cols">
        <li class="name"><a href="<%= edit_scheduled_event_path(scheduled_event) %>"><%= scheduled_event.event.name %> <%= image_tag("edit.png") %></a></li>
        <li class="status"><%= scheduled_event.status %></li>
        <li class="starts_at"><%= scheduled_event.starts_at %></li>
      </ol>
    </li>
  <% end %>
</ol>

app/views/penn_station/scheduled_events/edit.html.erb
<% content_for :toolbar_links do %>
  <li><a href="<%= scheduled_events_path %>">Back to all evens</a></li>
  <% if current_admin.has_role?("admin") %>
    <li><%= link_to "Delete this event", @scheduled_event, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
  <% end %>
<% end %>

<h1>Edit <%= @scheduled_event.event.name %></h1>
<%= render(:partial => "penn_station/scheduled_events/form", :locals => {:scheduled_event => @scheduled_event}) %>

app/views/penn_station/scheduled_events/index.html.erb
<% content_for :toolbar_links do %>
  <% if current_admin.has_role?("admin") %>
    <li class="event"><a href="<%= new_scheduled_event_path %>">Add a new event</a></li>
  <% end %>
<% end %>

<h1>Manage events</h1>

<ol id="<%= controller.controller_name %>_index" class="index">
  <li class="title-row row">
    <ol class="">
      <li class="name">Name</li>
      <li class="status">Status</li>
      <li class="starts_at">Starts At</li>
      <li class="calendar">Calendar</li>
    </ol>
  </li>

  <% @events.each do |event| %>
<%# binding.pry %>
<% next if event.scheduled_events.empty? %>
    <li id="<%= event.id %>" class="row <%= cycle("even", "odd") -%>">
      <ol class="cols">
        <li class="name"><a href="<%= edit_scheduled_event_path(event.scheduled_events[0]) %>"><%= event.name %> <%= image_tag("edit.png") %></a></li>
        <li class="status"><%= event.scheduled_events[0].status %></li>
        <li class="starts_at"><%= event.scheduled_events[0].starts_at %></li>
        <li class="calendar"><%= event.scheduled_events.map{|se| se.calendar.name}.join(",") %></li>
      </ol>
    </li>
  <% end %>
</ol>

app/views/penn_station/scheduled_events/new.html.erb
<% content_for :toolbar_links do %>
  <li><a href="<%= scheduled_events_path %>">Back to all events</a></li>
<% end %>

<h1>Create a new event</h1>
<%= render(:partial => "penn_station/scheduled_events/form", :locals => {:scheduled_event => @scheduled_event}) %>

app/views/penn_station/scheduled_events/show.html.erb
<% content_for :toolbar_links do %>
  <li><a href="<%= events_path %>">Back to all events</a></li>
  <% if current_admin.has_role?("admin") %>
    <li><%= link_to "Delete this event", @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
  <% end %>
<% end %>

<div id="<%= controller.controller_name %>">
  <% if current_admin.has_role?("admin","pennstation_admin") %>
    <h1>Manage <%= @event.name %></h1>
    <%= render(:partial => "penn_station/events/form", :locals => {:event => @event}) %>
  <% else %>
    <h1>Show <%= @event.name %></h1>
    <%= render(:partial => "penn_station/events/form", :locals => {:event => @event}) %>
  <% end %>
</div>